# Generated by Django 3.1 on 2020-12-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outputplot',
            fields=[
                ('outputplot_id', models.PositiveIntegerField(db_column='id', default=-1, primary_key=True, serialize=False)),
                ('x', models.CharField(max_length=256)),
                ('y', models.CharField(max_length=256)),
            ],
        ),
    ]
